version: '3'
services:
  web:
    build: .
    container_name: triagem_facil_web
    ports:
      - "5000:5000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - ELEVEN_LABS_KEY=${ELEVEN_LABS_KEY}
      - API_KEY=${API_KEY}
      - HOST=${HOST}
    volumes:
      - ./app:/app