name: "BuildRun Workflow"

on:
    workflow_call:
        inputs:
            environment:
                required: true
                type: string
        secrets:
            DOCKER_USERNAME:
                required: true
            DOCKER_PASSWORD:
                required: true
jobs:
    docker-build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Build Docker Image
              run: |
                docker build -t triagem_facil_web .

            - name: Push Docker Image to Registry
              run: |
                echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
                docker tag triagem_facil_web:latest ninjadexter/triagem_facil_web:latest
                docker push ninjadexter/triagem_facil_web:latest
